image: node:18

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - dist/
  
before_script:
  - npm install

build_master: 
  stage: build
  script:
  - npm run build --prod
  only: ['master']

deploy_master:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  script:
    - aws s3 sync ./dist s3://${BUCKET_NAME}/ --delete
    - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
  only: ['master']